### ISSUE TITLE
twilio account

### ISSUE THREAD

**Issue by victor-padovam** [diegogarciar/twilio_voice#21]
HI, I have doubts regarding where twillio's accessToken and AccountID is configured in the project's main.dart?

**Comment by diegogarciar** [comment]
Account ID should be configured server side, for access token, please refer to the package's documentation and example. I suggest you follow twillo's Quickstart guide for either iOS or Android,

**Comment by victor-padovam** [comment]
Now that I understand that it is configured in the funcions.js file, how does the server work

I made a server in PHP that also generates a jwt token.
My question:
in the role:  **TwilioVoice.instance.setTokens(accessToken: result.data, deviceToken: androidToken);**
in **accessToken: result.data**, I insert the token generated with my credentials by my server?

**Comment by diegogarciar** [comment]
Thats correct, the functions.js file was for a firebase functions server

**Comment by victor-padovam** [comment]
it worked, thank you.
