### ISSUE TITLE
TwilioVoice.instance.call.place ExtraOptions

### ISSUE THREAD

**Issue by victor-padovam** [diegogarciar/twilio_voice#34]
What methods can I use within ExtraOptions?
There is no readme

```
TwilioVoice.instance.call.place(
to: '74gDiewYbhaYsGtPcNsrmOMSoY82', 
from: userId!, 
extraOptions: {
   ????
});
```

**Comment by IzioDev** [comment]
https://github.com/diegogarciar/twilio_voice/blob/8de300c479861210849fb0e17bd0a847cf6fdb38/lib/twilio_voice.dart#L223

**Comment by diegogarciar** [comment]
its an optional field, if you don't need it you can leave it empty

**Comment by victor-padovam** [comment]
man thanks so much for the real answer. 
I noticed that it works without passing any parameters to it. more if I wanted to pass which parameter I need to pass to it?

**Comment by diegogarciar** [comment]
its custom, you can pass whatever you might need to initiate the call, if you don't need anything like me, it's fine.
